### ISSUE TITLE
The logical cutoffs for expected/ notExpected should be variable

### ISSUE THREAD

**Issue by sfacista** [tgen/snpSniffer#11]
Depending on the data-set, the hard-coded expected/notExpected .80 ratio may not be appropriate. In the next iteration, we should consider making the aforementioned ratio a variable that the user can input, or default to .80 if the user does not input a specific value.

**Comment by PedalheadPHX** [comment]
This can be controlled at the summary step with command line variables provided to the `summarize_snpSniffer.R` script in 6e1a488
