### ISSUE TITLE
Variant Calling

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/snpSniffer#12]
It looks like the variant calling is restrictive and is not calling all of the 382 sites in even high coverage genomes which is unexpected, this might explain why we are seeing higher correlation ratios than seen historically, need to investigate the reason

`

MMRF_2947_1_BM_CD138pos_T1_KHWGS.bwa.bam.snpSniffer | MMRF_2947_1_PB_WBC_C2_KHWGS.bwa.bam.snpSniffer | 265 | 261 | 0.984
-- | -- | -- | -- | --

`

**Comment by sfacista** [comment]
> It looks like the variant calling is restrictive and is not calling all of the 382 sites in even high coverage genomes which is unexpected, this might explain why we are seeing higher correlation ratios than seen historically, need to investigate the reason
> 
> `
> 
> MMRF_2947_1_BM_CD138pos_T1_KHWGS.bwa.bam.snpSniffer	MMRF_2947_1_PB_WBC_C2_KHWGS.bwa.bam.snpSniffer	265	261	0.984
> `

Will closing https://github.com/tgen/snpSniffer/issues/13 resolve this issue, or is it separate?

**Comment by PedalheadPHX** [comment]
yes fixed with #13
