### ISSUE TITLE
Remove the printed count of lines detected in the reference file.

### ISSUE THREAD

**Issue by awchrist** [tgen/snpSniffer#16]
@sfacista In the latest version of the jar with the -expected option (and maybe other options) the number of lines detected in the reference file is printed along with the output which breaks the required parsing of the output. 

Can you remove the printing of this information and push the new jar file?

**Comment by sfacista** [comment]
Line 48 of CountLines.java was ammended:
System.out.println(theCount + " lines detected in reference file.");
to 
// System.out.println(theCount + " lines detected in reference file.");

This pull request has been created:
https://github.com/tgen/snpSniffer/pull/17

All I could see was that it wanted to replace the .jar and .java. I show you are 1 commit ahead with another file, so please don't pull my old scripts if that is the case.

Or let me know if I need to resolve any conflicts.

**Comment by PedalheadPHX** [comment]
Fixed and released
