### ISSUE TITLE
Het count in while loop is missing CA

### ISSUE THREAD

**Issue by bryce-turner** [tgen/snpSniffer#19]
There is a typo here that is likely causing us to not count `CA` hets. I haven't performed any testing to confirm how problematic this typo is.

https://github.com/tgen/snpSniffer/blob/b59c54996469792ba3d9a2d77b1fd88b1031c854/src/Het.java#L75

**Comment by sfacista** [comment]
@bryce-turner I'll update this and re-release the built JAR so you can test .

**Comment by sfacista** [comment]
@bryce-turner please see pull request:
https://github.com/tgen/snpSniffer/pull/20

**Comment by PedalheadPHX** [comment]
Resolved in v7.0.1
